# Generated by Django 5.1.8 on 2025-04-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interaction', '0006_message_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openai_file_id', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('assistants', 'Assistants'), ('fine-tune', 'Fine-Tuning'), ('vision', 'Vision'), ('user_data', 'User Data')], default='assistants', max_length=50)),
                ('bytes_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openai_thread', to='interaction.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageOpenAIFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_files', to='interaction.message')),
                ('openai_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='openai_integration.openaifile')),
            ],
            options={
                'unique_together': {('message', 'openai_file')},
            },
        ),
    ]
