# Generated by Django 5.1.7 on 2025-04-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
