# Generated by Django 5.1.7 on 2025-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interaction", "0005_message_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
