# Generated by Django 5.1.7 on 2025-03-16 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Make this migration non-atomic

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        # Add this operation to delete all existing ratings before changing the ID type
        migrations.RunSQL(
            "DELETE FROM catalog_rating;",
            reverse_sql=migrations.RunSQL.noop  # No specific reverse operation needed if we're okay with data loss on rollback
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={},
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="review",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="rating",
            name="stars",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="catalog.aitool",
            ),
        ),
    ]
