# Generated by Django 5.1.5 on 2025-03-06 18:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_aitool_api_endpoint_aitool_api_model_aitool_api_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='context_length',
            field=models.IntegerField(default=4096, help_text='Maximum context length in tokens'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='input_price_per_million_tokens',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Price per million tokens for input/prompt', max_digits=10),
        ),
        migrations.AddField(
            model_name='aitool',
            name='modality',
            field=models.CharField(choices=[('text_to_text', 'Text to Text'), ('text_image_to_text', 'Text & Image to Text'), ('text_to_image', 'Text to Image'), ('text_to_audio', 'Text to Audio'), ('audio_to_text', 'Audio to Text')], default='text_to_text', max_length=50),
        ),
        migrations.AddField(
            model_name='aitool',
            name='output_price_per_million_tokens',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Price per million tokens for output/completion', max_digits=10),
        ),
        migrations.AddField(
            model_name='aitool',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='series',
            field=models.CharField(choices=[('gpt', 'GPT'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('llama', 'Llama'), ('mistral', 'Mistral'), ('palm', 'PaLM'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='aitool',
            name='supports_json_mode',
            field=models.BooleanField(default=False, help_text='Supports JSON mode for structured outputs'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='supports_tools',
            field=models.BooleanField(default=False, help_text='Supports function calling/tools'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='Supports image inputs'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='api_type',
            field=models.CharField(choices=[('openai', 'OpenAI API'), ('huggingface', 'Hugging Face API'), ('anthropic', 'Anthropic API'), ('google', 'Google AI API'), ('custom', 'Custom Integration'), ('none', 'No Integration')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='category',
            field=models.CharField(choices=[('general', 'General Purpose'), ('image_gen', 'Image Generation'), ('transcription', 'Transcription'), ('word_processor', 'Word Processor'), ('roleplay', 'Roleplay'), ('programming', 'Programming'), ('marketing', 'Marketing'), ('research', 'Research'), ('creative', 'Creative Writing'), ('data_analysis', 'Data Analysis')], max_length=100),
        ),
    ]
