# Generated by Django 5.1.7 on 2025-04-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tool_logos/"),
        ),
    ]
