# Generated by Django 5.1.7 on 2025-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_aitool_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("OPENAI", "OpenAI API"),
                    ("HUGGINGFACE", "Hugging Face API"),
                    ("ANTHROPIC", "Anthropic API"),
                    ("GOOGLE", "Google AI API"),
                    ("CUSTOM", "Custom API"),
                    ("NONE", "No API Integration"),
                    ("GEMINI", "Google Gemini API"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
