# Generated by Django 5.1.9 on 2025-05-13 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Make this migration non-atomic

    dependencies = [
        ('catalog', '0007_alter_aitool_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='new_id',
            # Temporarily allow null, default will ensure population for existing rows if any
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True), 
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
