# Generated by Django 5.1.9 on 2025-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_rating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/tool_images/'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
