# Generated by Django 5.1.8 on 2025-04-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interaction', '0006_message_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gemini_file_id', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('general', 'General Use'), ('vision', 'Vision'), ('document', 'Document Analysis'), ('audio', 'Audio Analysis'), ('video', 'Video Analysis')], default='general', max_length=50)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('bytes_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageGeminiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gemini_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='gemini_integration.geminifile')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_files', to='interaction.message')),
            ],
            options={
                'unique_together': {('message', 'gemini_file')},
            },
        ),
    ]
